### ISSUE TITLE
Sensitive data returned from REST call

### ISSUE THREAD

**Issue by Letaguator** [OpenDataNTNU/OpenData#101]
In MetadataController the following REST call returns sensitive data.

[HttpPut("{uuid}/experience")]
public async Task<IActionResult> SetExperience([FromBody] SaveExperiencePostResource experienceResource, string uuid);

Sensitive data seems to be token, hashed password and password salt.
[EDITED]

**Comment by petterroea** [comment]
but _what_ sensitive data

**Comment by petterroea** [comment]
This isn't a bug report, its a statement about a method

**Comment by Letaguator** [comment]
Token, hashed password and password salt as far as I know.

**Comment by petterroea** [comment]
Example?

**Comment by Letaguator** [comment]
Look at #100, if that is fixed before merged this issue is not relevant.

**Comment by Letaguator** [comment]
The user object attached to the experience is not sanitised if I am not mistaken

**Comment by petterroea** [comment]
What i am saying is that this issue is literally uselss. It isn't a bug report. There is no information about _what_ is being leaked. Show code and json blobs that show what it returns and what is wrong with it.

**Comment by petterroea** [comment]
I need to know:

 * What is expected
 * What is happening(show code)
 * Method of easily reproducing it

See https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by Letaguator** [comment]
I created this issue quickly in the event that I and Andreas had merge the other branch with the error, and to ensure that it was not forgotten. I can update it later, as I am not running the project atm. I refer to the chat in #100. If you have time you can fix the issue, and we can close and ignore this issue.

**Comment by petterroea** [comment]
I do not, and you should not expect anyone to, have time to manually dig through the code to find out what you think is a sensitive data leak. This is why guidelines for writing bug reports exist. Making tickets with "X doesnt work" is more than just useless, its a waste of time for everyone involved.

This is well documented, most places that receive bug reports have strict rules/templates on what a bug report should contain. There is a reason github now provides automatic templates for issues.

**Comment by Letaguator** [comment]
Please read #100! I did not even discover this bug, but created the issue as an curtesy for the group. I also planned to fill it out when I have time to fire up the project and test it myself.

**Comment by petterroea** [comment]
I have read #100. But creating an issue like this is not a good solution. If you are going to make an issue, fill out context like a proper bug report.

**Comment by Letaguator** [comment]
It is a better than not doing anything, merging it and forgetting about it! I created this as a remainder. And may I restate that I plan to update it when I have time! The best would have been to fix #100, and ensured it merged correctly to begin with.

But after no response regarding the #100 I created this in-case me and Andreas would end up merging #100 nevertheless.

**Comment by petterroea** [comment]
But it lacks context allowing others to carry out the task. Its better to take the extra 5 minutes to create a proper bug report that anyone can carry out, preferably without having to even read other issues and dig for context.

The last thing we want is a bunch of issues where one person knows the context and is going to fix it later :tm:

**Comment by Letaguator** [comment]
Fine, I will close the issue, and create another later. But I find this very nitty gritty and unnecessary. As a note, the person who found this bug should have created an issue! I assumed you knew of the issue as well from the context of #100.

**Comment by petterroea** [comment]
I am not asking you to close it, i am asking you to improve the quality so its a good bug report that is easy to deal with.

**Comment by Letaguator** [comment]
This was resolved in the merge^
