### ISSUE TITLE
Add metadata type search options

### ISSUE THREAD

**Issue by petterroea** [OpenDataNTNU/OpenData#116]
# Short description

Business owners should be able to filter by at least tag and name.

This issue consists of:

 * `/api/metadataType/by/tags`
 * `/api/metadataType/by/name`

# Dependencies

**Comment by Letaguator** [comment]
I suggest this issue (https://github.com/OpenDataNTNU/OpenData/issues/175) can unify searching/filtering based on name, tags and keywords
