### ISSUE TITLE
Create private routes and public routes

### ISSUE THREAD

**Issue by AndreasJJ** [OpenDataNTNU/OpenData#12]
# Short description

Setup private and public routes (this is done by checking if the user object exists in global state)

# Dependencies

issue #11

**Comment by AndreasJJ** [comment]
Didnt write it in the description, but we should have a route type that only allows not-logged-in users to view the route (like only not-logged-in users should be able to view login and register) @MittBrukernavn

**Comment by MittBrukernavn** [comment]
Can do
