### ISSUE TITLE
Handle expired token

### ISSUE THREAD

**Issue by AndreasJJ** [OpenDataNTNU/OpenData#132]
# Short description

The token can expire after x amount of times, and all actions that require auth will just fail without saying why as there's no handling for token refreshing or discovery
# Dependencies

Mention dependencies here

**Comment by Letaguator** [comment]
Do we want to add refresh tokens?
Or do we instead just want to redirect the user to the login page if "401 Unauthorized" is returned?

**Comment by AndreasJJ** [comment]
We can't redirect them on 401 Unauthorized because the server can return that on some endpoints even if the token is valid.

**Comment by Letaguator** [comment]
Which endpoints are these?

**Comment by AndreasJJ** [comment]
Can't remember exactly, but think login uses it and likes. So it wouldn't make sense to redirect them. Also doing so manually would mean you'd have to do it like on very fetch call or rewrite a custom api around the fetch api

**Comment by Letaguator** [comment]
So we want to implement refresh tokens?
