### ISSUE TITLE
Creation of Experience Post has bugs

### ISSUE THREAD

**Issue by Letaguator** [OpenDataNTNU/OpenData#157]
- It is possible to create an experience post even though you are not from the given municipality of the data set. To reproduce create an experience post on an issue that have another municipality than the user you are testing with.

- ~~It is also possible to overwrite an article by saving the URL and UUID and thereby manually injecting an article again.~~

**Comment by AndreasJJ** [comment]
"It is also possible to overwrite an article by saving the URL and UUID and thereby manually injecting an article again." should be solved with story 23 #193, the first point still stands for the backend. The frontend is already "hiding" it away from users.
