### ISSUE TITLE
Name for Metadata

### ISSUE THREAD

**Issue by Letaguator** [OpenDataNTNU/OpenData#84]
Metadata should have a name with it's description.

**Comment by petterroea** [comment]
This has already been discussed and clarified on discord

**Comment by Letaguator** [comment]
Can you clarify it here, we are all sitting in a meeting wondering why not.

**Comment by Letaguator** [comment]
I suddenly realised it does not make sense to give a name since it already belongs to a MetadataType. At least that is what I assume is the reasoning.
